# Generated by Django 4.1.4 on 2023-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
