# Generated by Django 4.1.4 on 2023-01-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Hostel_Name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Phone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Roll_No',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
