# Generated by Django 4.1.4 on 2023-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0003_student_hostel_name_student_phone_no_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('user_Name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=15)),
                ('Hostel_Assigned', models.CharField(max_length=25)),
                ('warden_id', models.CharField(max_length=20)),
            ],
        ),
    ]
