# Generated by Django 4.1.4 on 2023-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0004_warden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('user_Name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=15)),
            ],
        ),
    ]
