# Generated by Django 4.1.4 on 2023-01-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0005_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
