# Generated by Django 4.1.4 on 2023-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maincommunication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
