# Generated by Django 4.1.4 on 2023-01-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maincommunication', '0002_alter_outpass_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outpass',
        ),
    ]
