# Generated by Django 4.1.4 on 2023-01-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maincommunication', '0003_delete_outpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('roll', models.CharField(max_length=15)),
                ('Hostel', models.CharField(max_length=25)),
                ('Reason', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('Phone_no', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(default='Not yet accepted', max_length=50)),
            ],
        ),
    ]
