# Generated by Django 4.1.4 on 2023-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maincommunication', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='time',
            field=models.IntegerField(),
        ),
    ]
