# Generated by Django 4.1.4 on 2023-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maincommunication', '0005_alter_outpass_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='time',
            field=models.CharField(max_length=1000),
        ),
    ]
